### ISSUE TITLE
Stats after a command run

### ISSUE THREAD

**Issue by alexanderad** [innogames/polysh#17]
I often find myself running some debug commands on a group of servers, doing grep operations. Every time I use `grep I'm thinking that it would be nice to have is some stats of the command run.

Say you have 20 servers in a session, you run something like `cat my-text-file | grep my-text-string` and you receive only 5-6 results back. There is no way to tell quickly how many servers do have something in the file and how many returned nothing. The output of servers having no match is absent, which is expected behavior. One way I use as a workaround is that I run a command in question and then right after I run `echo $?`, which gives me 0 or 1, depending on the exit code, where zeros stand for "there is grep match" and ones for "no match", as per grep exit code reference. In this case all servers report back their exit codes.

I wonder if we can add (maybe an optional, behind a flag, like `--retcode-stats`) feature, where the prompt does return some stats:
```bash
ready(28)> cat my-text-file | grep my-text-string
...
ready(28, exit 0:17,  1:8, 127:3)>
```
Maybe with some color coding.

**Comment by kofrezo** [comment]
Hi @alexanderad 
I think your approach evaluating the return code is already correct. How about using `||` and `&&` features of the shell and `-q` parameter of grep.
```
read(28) > grep my-test-string || echo "No Matches"
somehost.example.com: No Matches
```
This should give you what you want - no ?

Besides I see value in making the return code of the last command available and will check if that is possible.
