### ISSUE TITLE
Prompt stuck waiting when using tcsh as the remote shell

### ISSUE THREAD

**Issue by northmirko** [innogames/polysh#21]
Hi there,

We have some production Linux machines\VMs, that don't come with installed zsh shell.
I saw that this set of commands is issued by polysh during session setup, and do not execute properly:

`unsetopt zle 2 > /dev/null ; stty -echo -onlcr -ctlecho ; PS2= ; RPS1= ; RPROMPT= ; PROMPT_COMMAND= ; TERM=ansi ; unset precmd_functions ; unset HISTFILE ; PS1="polysh""-Hw3iP:prompt:b2CQr:1/`

Result:
`Unmatched ".`

After this, sessions stay in *waiting* state.
Example for two machines:
*waiting (2/2)>*

During code review I saw that your code relies on presumption that zsh is supported on server machine, maybe I'm wrong.
We can't install zsh, some contract issues.
Also our default shell is tcsh, so mechanism of env. variable setting is different. 

Is there any option for polysh to use bash, tsch ... for initial session setup ?
> Maybe, make polysh check if zsh is installed, if not, instruct it to uses other available type of shells.

**Comment by RonjaPonja** [comment]
Polysh used to always spawn bash on the remote side, but now we just start your users default shell or no shell at all if you use --command[ #13 ]. Polysh has support for both bash as well as zsh[ #15 ] on the remote side and we would gladly accept patches for more shells.

If you don't want to write the patch to support tcsh, you can either change the default shell on the remote system to bash or you can alias polysh to something like ```polysh --ssh "exec ssh -oLogLevel=Quiet -t %(host)s %(port)s exec bash"``` in your local shell.
